[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "1.0.3"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/fedor35/ncalayer-rs"
authors = ["Fedor Gubenkov <cto@teplosmart.kz>"]

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
