//! Tests against the Kalkan-produced XML fixtures (`tests/fixtures/test_gost512.xml_*`,
//! generated by `tools/java-oracle xml`) and a cross-check of our own
//! signatures by the Kalkan oracle (`tools/java-oracle/run.sh verifyxml`).

use std::path::{Path, PathBuf};
use std::process::Command;

use kz_pki::{Cert, Entry, KeyStore};
use kz_xmldsig::{sign_by_id, sign_enveloped, sign_enveloped_many, verify, Error};

fn fixture(name: &str) -> String {
    let p = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures")
        .join(name);
    std::fs::read_to_string(&p).unwrap_or_else(|e| panic!("{}: {e}", p.display()))
}

fn entry() -> Entry {
    let p = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/test_gost512.p12");
    KeyStore::open_file(p, "Test1234")
        .unwrap()
        .entries
        .remove(0)
}

fn rng() -> rand::rngs::StdRng {
    use rand::SeedableRng;
    rand::rngs::StdRng::seed_from_u64(0x5eed)
}

// ----- Kalkan fixtures ------------------------------------------------------

/// The first question: which byte order does Kalkan use for the GOST
/// `SignatureValue`?  The fixtures verify with `Signature::from_bytes_kz`
/// (`r ‖ s`, little-endian) — the layout `verify` uses.
#[test]
fn kalkan_fixtures_verify() {
    for name in [
        "test_gost512.xml_simple.xml",
        "test_gost512.xml_ns.xml",
        "test_gost512.xml_xpath.xml",
    ] {
        let reports = verify(&fixture(name)).unwrap_or_else(|e| panic!("{name}: {e}"));
        assert_eq!(reports.len(), 1, "{name}");
        let r = &reports[0];
        assert_eq!(r.algorithm, kz_xmldsig::SignerAlgorithm::Gost2015_512);
        assert_eq!(r.cert.subject_cn().as_deref(), Some("TEST GOST512"));
        let expected_uri = if name.contains("xpath") { "#part" } else { "" };
        assert_eq!(r.references, vec![expected_uri.to_string()], "{name}");
        assert_eq!(r.canonicalization.exclusive, name.contains("xpath"));
    }
}

#[test]
fn kalkan_fixture_cert_matches_pem() {
    let pem = Cert::from_pem(&fixture("test_gost512.cer.pem")).unwrap();
    let r = verify(&fixture("test_gost512.xml_simple.xml")).unwrap();
    assert_eq!(r[0].cert.as_der(), pem.as_der());
}

/// Flipping a byte of the signed text or of the signature must fail.
#[test]
fn kalkan_fixtures_tampered() {
    let simple = fixture("test_gost512.xml_simple.xml");
    let tampered = simple.replacen("<a>1</a>", "<a>2</a>", 1);
    assert!(matches!(verify(&tampered), Err(Error::DigestMismatch(u)) if u.is_empty()));

    let xpath = fixture("test_gost512.xml_xpath.xml");
    let tampered = xpath.replacen("<x>1</x>", "<x>2</x>", 1);
    assert!(matches!(verify(&tampered), Err(Error::DigestMismatch(u)) if u == "#part"));
    // Content outside the referenced element is not covered.
    let outside = xpath.replacen("<b/>", "<b>free</b>", 1);
    assert!(verify(&outside).is_ok());

    // SignatureValue tampering (first base64 character of the value).
    let sv = simple.find("<ds:SignatureValue>\n").unwrap() + "<ds:SignatureValue>\n".len();
    let mut bytes = simple.clone().into_bytes();
    bytes[sv] = if bytes[sv] == b'A' { b'B' } else { b'A' };
    assert!(matches!(
        verify(std::str::from_utf8(&bytes).unwrap()),
        Err(Error::BadSignature)
    ));

    // SignedInfo tampering (digest value) breaks the signature even if the digest matched.
    let di = simple.replacen(
        "Algorithm=\"urn:ietf:params:xml:ns:pkigovkz:xmlsec:algorithms:gostr34112015-512\"",
        "Algorithm=\"urn:ietf:params:xml:ns:pkigovkz:xmlsec:algorithms:gostr34112015-512\" x=\"y\"",
        1,
    );
    assert!(matches!(verify(&di), Err(Error::BadSignature)));
}

// ----- our own signatures ---------------------------------------------------

/// Our `ds:Signature` has the same layout as Kalkan's: replacing the three
/// value-carrying text nodes makes the texts identical.
#[test]
fn own_signature_text_matches_fixture_layout() {
    let e = entry();
    for (input, reference) in [
        (
            "test_gost512.xml_simple.input.xml",
            "test_gost512.xml_simple.xml",
        ),
        ("test_gost512.xml_ns.input.xml", "test_gost512.xml_ns.xml"),
    ] {
        let signed = sign_enveloped(&e, &fixture(input), &mut rng()).unwrap();
        assert_eq!(
            strip_values(&signed),
            strip_values(&fixture(reference)),
            "{input}"
        );
        verify(&signed).unwrap();
    }
    let signed = sign_by_id(
        &e,
        &fixture("test_gost512.xml_xpath.input.xml"),
        "/root/a",
        "/root",
        &mut rng(),
    )
    .unwrap();
    assert_eq!(
        strip_values(&signed),
        strip_values(&fixture("test_gost512.xml_xpath.xml"))
    );
    verify(&signed).unwrap();
}

/// Replace the (random) SignatureValue and the XML declaration — Santuario's
/// serializer drops the declaration, we keep the caller's text.
fn strip_values(xml: &str) -> String {
    let s = xml.replace("<?xml version=\"1.0\" encoding=\"UTF-8\"?>", "");
    let a = s.find("<ds:SignatureValue>").unwrap();
    let b = s.find("</ds:SignatureValue>").unwrap();
    format!("{}<ds:SignatureValue>…{}", &s[..a], &s[b..])
}

/// The digest of the enveloped reference is deterministic, so our
/// `DigestValue` must equal Kalkan's — this pins the C14N of the content.
#[test]
fn own_digest_values_equal_kalkan() {
    let e = entry();
    for (input, reference, by_id) in [
        (
            "test_gost512.xml_simple.input.xml",
            "test_gost512.xml_simple.xml",
            false,
        ),
        (
            "test_gost512.xml_ns.input.xml",
            "test_gost512.xml_ns.xml",
            false,
        ),
        (
            "test_gost512.xml_xpath.input.xml",
            "test_gost512.xml_xpath.xml",
            true,
        ),
    ] {
        let signed = if by_id {
            sign_by_id(&e, &fixture(input), "/root/a", "/root", &mut rng()).unwrap()
        } else {
            sign_enveloped(&e, &fixture(input), &mut rng()).unwrap()
        };
        assert_eq!(
            digest_value(&signed),
            digest_value(&fixture(reference)),
            "{input}"
        );
    }
}

fn digest_value(xml: &str) -> String {
    let a = xml.find("<ds:DigestValue>").unwrap() + "<ds:DigestValue>".len();
    let b = xml.find("</ds:DigestValue>").unwrap();
    xml[a..b].to_string()
}

#[test]
fn sign_many_and_tamper_own() {
    let e = entry();
    let docs = vec!["<a><b>x</b></a>".to_string(), "<c attr=\"1\"/>".to_string()];
    let signed = sign_enveloped_many(&e, &docs, &mut rng()).unwrap();
    assert_eq!(signed.len(), 2);
    assert!(signed[1].starts_with("<c attr=\"1\"><ds:Signature"));
    assert!(signed[1].ends_with("</ds:Signature></c>"));
    for s in &signed {
        verify(s).unwrap();
    }
    let tampered = signed[0].replacen("<b>x</b>", "<b>y</b>", 1);
    assert!(matches!(verify(&tampered), Err(Error::DigestMismatch(_))));
}

#[test]
fn sign_keeps_text_and_declaration() {
    let e = entry();
    let xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- c --><doc xmlns=\"urn:d\" xml:lang=\"ru\"><a>  текст &amp; <![CDATA[<x>]]> </a><?pi data?></doc>\n";
    let signed = sign_enveloped(&e, xml, &mut rng()).unwrap();
    assert!(signed.starts_with("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- c --><doc xmlns=\"urn:d\" xml:lang=\"ru\"><a>  текст &amp; <![CDATA[<x>]]> </a><?pi data?><ds:Signature"));
    assert!(signed.ends_with("</ds:Signature></doc>\n"));
    verify(&signed).unwrap();
}

#[test]
fn sign_by_id_errors() {
    let e = entry();
    assert!(matches!(
        sign_by_id(
            &e,
            "<root><a><x/></a></root>",
            "/root/a",
            "/root",
            &mut rng()
        ),
        Err(Error::MissingId)
    ));
    assert!(matches!(
        sign_by_id(
            &e,
            "<root><a Id=\"p\"/></root>",
            "/root/a",
            "/root/a",
            &mut rng()
        ),
        Err(Error::TbsIsParent)
    ));
    assert!(matches!(
        sign_by_id(
            &e,
            "<root><a Id=\"p\"/></root>",
            "/root/b",
            "/root",
            &mut rng()
        ),
        Err(Error::XPathNoMatch(_))
    ));
    assert!(matches!(
        sign_by_id(&e, "<root><a Id=\"p\"/></root>", "//a", "/root", &mut rng()),
        Err(Error::XPathUnsupported(_))
    ));
    // Indexed step, empty parent element, signature inside a non-root parent.
    let signed = sign_by_id(
        &e,
        "<root><a Id=\"one\"/><a Id=\"two\"><y/></a><sig/></root>",
        "/root/a[2]",
        "/root/sig",
        &mut rng(),
    )
    .unwrap();
    assert!(signed.contains("<sig><ds:Signature"));
    assert!(signed.contains("URI=\"#two\""));
    assert!(signed.ends_with("</ds:Signature></sig></root>"));
    let r = verify(&signed).unwrap();
    assert_eq!(r[0].references, vec!["#two".to_string()]);
}

// ----- cross-check by the Kalkan oracle ------------------------------------

fn oracle() -> Option<PathBuf> {
    let run = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tools/java-oracle/run.sh");
    let jar = std::env::var_os("KALKAN_JAR")
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var_os("HOME").map(|h| {
                PathBuf::from(h)
                    .join(".config/NCALayer/ncalayer-cache/bundle10/version0.0/bundle.jar")
            })
        })?;
    if run.is_file() && jar.is_file() && Command::new("java").arg("-version").output().is_ok() {
        Some(run)
    } else {
        None
    }
}

fn oracle_verifyxml(run: &Path, xml: &Path) -> String {
    let out = Command::new(run)
        .arg("verifyxml")
        .arg(xml)
        .output()
        .expect("run oracle");
    let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
    assert!(
        out.status.success(),
        "oracle failed: {stdout}\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    stdout.lines().last().unwrap_or("").trim().to_string()
}

#[test]
fn kalkan_oracle_verifies_our_xml() {
    let Some(run) = oracle() else {
        eprintln!("skipped: Kalkan oracle (JDK + NCALayer bundle.jar) not available");
        return;
    };
    let dir = std::env::temp_dir().join(format!("kz-xmldsig-oracle-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let e = entry();
    let cases = [
        (
            "simple",
            sign_enveloped(
                &e,
                &fixture("test_gost512.xml_simple.input.xml"),
                &mut rng(),
            )
            .unwrap(),
        ),
        (
            "ns",
            sign_enveloped(&e, &fixture("test_gost512.xml_ns.input.xml"), &mut rng()).unwrap(),
        ),
        (
            "xpath",
            sign_by_id(
                &e,
                &fixture("test_gost512.xml_xpath.input.xml"),
                "/root/a",
                "/root",
                &mut rng(),
            )
            .unwrap(),
        ),
    ];
    for (name, xml) in cases {
        let p = dir.join(format!("{name}.xml"));
        std::fs::write(&p, &xml).unwrap();
        let verdict = oracle_verifyxml(&run, &p);
        assert_eq!(verdict, "VALID", "{name}: {xml}");
    }
    // Kalkan must reject a tampered document too (sanity of the oracle).
    let bad = cases_tampered(&e);
    let p = dir.join("tampered.xml");
    std::fs::write(&p, &bad).unwrap();
    assert!(oracle_verifyxml(&run, &p).starts_with("INVALID"));
    let _ = std::fs::remove_dir_all(&dir);
}

fn cases_tampered(e: &Entry) -> String {
    sign_enveloped(e, "<root><a>1</a></root>", &mut rng())
        .unwrap()
        .replacen("<a>1</a>", "<a>2</a>", 1)
}

/// Negative probe of the byte order: the fixture's `SignatureValue` verifies
/// only as `r ‖ s` little-endian (`from_bytes_kz`), not as the RFC 4491
/// `s ‖ r` big-endian layout nor as the standard's `r ‖ s` big-endian.
#[test]
fn kalkan_signature_value_byte_order() {
    use kz_xmldsig::dom::Document;
    use kz_xmldsig::{canonicalize, Method};
    let xml = fixture("test_gost512.xml_simple.xml");
    let doc = Document::parse(&xml).unwrap();
    let sig = doc.descendants_named(Some("http://www.w3.org/2000/09/xmldsig#"), "Signature")[0];
    let si = doc
        .element(
            sig,
            Some("http://www.w3.org/2000/09/xmldsig#"),
            "SignedInfo",
        )
        .unwrap();
    let sv = doc
        .element(
            sig,
            Some("http://www.w3.org/2000/09/xmldsig#"),
            "SignatureValue",
        )
        .unwrap();
    let canon = canonicalize(&doc, si, None, Method::INCLUSIVE);
    let sig_bytes = kz_xmldsig::algo::base64_decode(&doc.text(sv)).unwrap();
    let cert = Cert::from_pem(&fixture("test_gost512.cer.pem")).unwrap();
    let (x, y) = match cert.public_key().unwrap() {
        kz_pki::PublicKey::Gost2015 { x, y, .. } => (x, y),
        _ => panic!(),
    };
    let curve = gost3410::NamedCurve::Tc26Gost3410_12_512ParamSetA.curve();
    let mut le: Vec<u8> = x.iter().rev().copied().collect();
    le.extend(y.iter().rev());
    let pk = gost3410::PublicKey::from_bytes_x509(curve, &le).unwrap();
    let digest = gost3410::HashAlg::Streebog512.digest(&canon);
    let ok = |s: gost3410::Result<gost3410::Signature>| {
        s.map(|s| gost3410::verify(curve, &pk, &digest, &s))
            .unwrap_or(false)
    };
    assert!(
        ok(gost3410::Signature::from_bytes_kz(curve, &sig_bytes)),
        "r‖s LE must verify"
    );
    assert!(
        !ok(gost3410::Signature::from_bytes_rfc4491(curve, &sig_bytes)),
        "s‖r BE must not"
    );
    assert!(
        !ok(gost3410::Signature::from_bytes_gost(curve, &sig_bytes)),
        "r‖s BE must not"
    );
}
