//! Tests against CMS files produced by the real Kalkan provider
//! (`tests/fixtures/test_gost512.*`, generated by `tools/java-oracle`) and a
//! cross-check of our output by the same oracle when it is available.

use std::path::{Path, PathBuf};
use std::process::Command;

use gost3410::{NamedCurve, PublicKey, Signature};
use kz_cms::{
    add_signer, create_cades_bes, create_cades_bes_from_hash, verify, Content, Error, Nonce,
    SignedData, SignedDataBuilder, SignerAlgorithm,
};
use kz_pki::{Cert, Entry, KeyStore};
use time::macros::datetime;
use time::OffsetDateTime;

const ATTACHED: &[u8] = include_bytes!("../../../tests/fixtures/test_gost512.attached.cms");
const DETACHED: &[u8] = include_bytes!("../../../tests/fixtures/test_gost512.detached.cms");
const MESSAGE: &[u8] = include_bytes!("../../../tests/fixtures/test_message.txt");
const P12: &[u8] = include_bytes!("../../../tests/fixtures/test_gost512.p12");
const CER_PEM: &str = include_str!("../../../tests/fixtures/test_gost512.cer.pem");
const VECTORS: &str = include_str!("../../../tests/fixtures/test_gost512.vectors");
const PASSWORD: &str = "Test1234";
/// `signingTime` of the attached fixture (UTCTime 261002174309Z).
const FIXTURE_TIME: OffsetDateTime = datetime!(2026-10-02 17:43:09 UTC);

fn entry() -> Entry {
    KeyStore::open(P12, PASSWORD).unwrap().entries.remove(0)
}

fn vector(key: &str) -> Vec<u8> {
    let v = VECTORS
        .lines()
        .find_map(|l| l.strip_prefix(&format!("{key}=")))
        .unwrap();
    hex::decode(v).unwrap()
}

fn rng() -> rand::rngs::StdRng {
    use rand::SeedableRng;
    rand::rngs::StdRng::seed_from_u64(0x5eed)
}

// ----- the first question: how does Kalkan lay out the GOST signature? -------

#[test]
fn kalkan_signer_info_signature_is_r_le_s_le() {
    let sd = SignedData::from_der(ATTACHED).unwrap();
    let si = &sd.signer_infos[0];
    assert_eq!(si.signature.len(), 128);
    let curve = NamedCurve::Tc26Gost3410_12_512ParamSetA.curve();
    let spki = vector("spki");
    let q = PublicKey::from_bytes_x509(curve, &spki[spki.len() - 128..]).unwrap();
    // The signed bytes are the signed attributes re-tagged as SET.
    let mut signed = si.signed_attrs_raw.clone().unwrap();
    signed[0] = 0x31;
    let digest = SignerAlgorithm::Gost2015_512.digest(&signed);
    let kz = Signature::from_bytes_kz(curve, &si.signature).unwrap();
    assert!(
        gost3410::verify(curve, &q, &digest, &kz),
        "Kalkan CMS signature must be r_LE || s_LE (same as NCA X.509)"
    );
    let rfc = Signature::from_bytes_rfc4491(curve, &si.signature).unwrap();
    assert!(
        !gost3410::verify(curve, &q, &digest, &rfc),
        "RFC 4491 s_BE || r_BE layout must NOT verify"
    );
}

// ----- verification of the Kalkan fixtures ----------------------------------

#[test]
fn verifies_attached_fixture() {
    let r = verify(ATTACHED, Content::Attached, &[]).unwrap();
    assert_eq!(r.len(), 1);
    assert_eq!(r[0].algorithm, SignerAlgorithm::Gost2015_512);
    assert_eq!(r[0].signing_time, Some(FIXTURE_TIME));
    assert_eq!(r[0].message_digest, vector("digest"));
    assert_eq!(r[0].cert.subject_cn().as_deref(), Some("TEST GOST512"));
    assert!(r[0].timestamp.is_none());
    // Also with the content supplied explicitly.
    verify(ATTACHED, Content::Detached(MESSAGE), &[]).unwrap();
    verify(ATTACHED, Content::Digest(&vector("digest")), &[]).unwrap();
}

#[test]
fn verifies_detached_fixture() {
    let sd = SignedData::from_der(DETACHED).unwrap();
    assert!(sd.content.is_none());
    verify(DETACHED, Content::Detached(MESSAGE), &[]).unwrap();
    verify(DETACHED, Content::Digest(&vector("digest")), &[]).unwrap();
    assert!(matches!(
        verify(DETACHED, Content::Attached, &[]),
        Err(Error::ContentRequired)
    ));
}

#[test]
fn verifies_with_external_certificate() {
    // Strip the certificates from the fixture and supply the certificate separately.
    let mut b = SignedDataBuilder::new(MESSAGE, true);
    b.add_signer(&entry(), FIXTURE_TIME, Nonce::Deterministic)
        .unwrap();
    let cms = b.build();
    let sd = SignedData::from_der(&cms).unwrap();
    assert_eq!(sd.certificates.len(), 1);
    let cert = Cert::from_pem(CER_PEM).unwrap();
    verify(&cms, Content::Attached, &[cert]).unwrap();
}

#[test]
fn rejects_modified_content() {
    let mut wrong = MESSAGE.to_vec();
    wrong[0] ^= 1;
    assert!(matches!(
        verify(DETACHED, Content::Detached(&wrong), &[]),
        Err(Error::DigestMismatch)
    ));
    // Attached: flip a byte of the embedded content (the digest no longer matches).
    let mut cms = ATTACHED.to_vec();
    let pos = cms
        .windows(MESSAGE.len())
        .position(|w| w == MESSAGE)
        .unwrap();
    cms[pos] ^= 1;
    assert!(matches!(
        verify(&cms, Content::Attached, &[]),
        Err(Error::DigestMismatch)
    ));
}

#[test]
fn rejects_modified_signature_and_attributes() {
    let sd = SignedData::from_der(ATTACHED).unwrap();
    let sig = &sd.signer_infos[0].signature;
    let mut cms = ATTACHED.to_vec();
    let pos = cms
        .windows(sig.len())
        .position(|w| w == sig.as_slice())
        .unwrap();
    cms[pos + 5] ^= 1;
    assert!(matches!(
        verify(&cms, Content::Attached, &[]),
        Err(Error::BadSignature)
    ));
    // Flip a byte of signingTime inside the signed attributes.
    let mut cms = ATTACHED.to_vec();
    let pos = cms.windows(13).position(|w| w == b"261002174309Z").unwrap();
    cms[pos + 11] = b'8';
    assert!(matches!(
        verify(&cms, Content::Attached, &[]),
        Err(Error::BadSignature)
    ));
}

// ----- byte-for-byte structure against the fixture --------------------------

/// Return the file with the 128 signature bytes of the first signer zeroed.
fn mask_signature(cms: &[u8]) -> Vec<u8> {
    let sd = SignedData::from_der(cms).unwrap();
    let sig = sd.signer_infos[0].signature.clone();
    assert_eq!(sig.len(), 128);
    let mut out = cms.to_vec();
    let pos = out.windows(128).position(|w| w == sig.as_slice()).unwrap();
    out[pos..pos + 128].fill(0);
    out
}

#[test]
fn attached_matches_fixture_except_signature() {
    let mut b = SignedDataBuilder::new(MESSAGE, true);
    b.add_signer(&entry(), FIXTURE_TIME, Nonce::Deterministic)
        .unwrap();
    let ours = b.build();
    assert_eq!(ours.len(), ATTACHED.len(), "length differs");
    assert_eq!(
        hex::encode(mask_signature(&ours)),
        hex::encode(mask_signature(ATTACHED))
    );
}

#[test]
fn detached_matches_fixture_except_signature() {
    let sd = SignedData::from_der(DETACHED).unwrap();
    let t = sd.signer_infos[0].signing_time().unwrap().unwrap();
    let mut b = SignedDataBuilder::new(MESSAGE, false);
    b.add_signer(&entry(), t, Nonce::Deterministic).unwrap();
    let ours = b.build();
    assert_eq!(
        hex::encode(mask_signature(&ours)),
        hex::encode(mask_signature(DETACHED))
    );
    // Hash-only signing yields the very same detached structure.
    let mut h = SignedDataBuilder::hash_only();
    h.add_signer_with_digest(&entry(), &vector("digest"), t, Nonce::Deterministic)
        .unwrap();
    assert_eq!(mask_signature(&h.build()), mask_signature(DETACHED));
}

// ----- round trips ----------------------------------------------------------

#[test]
fn round_trip_attached() {
    let now = OffsetDateTime::now_utc();
    let cms = create_cades_bes(&entry(), MESSAGE, true, now, &mut rng()).unwrap();
    let r = verify(&cms, Content::Attached, &[]).unwrap();
    assert_eq!(
        r[0].signing_time.unwrap().unix_timestamp(),
        now.unix_timestamp()
    );
    let cms2 = create_cades_bes(&entry(), MESSAGE, true, now, &mut rng()).unwrap();
    assert_eq!(cms, cms2, "same seed, same output");
}

#[test]
fn round_trip_detached() {
    let cms = create_cades_bes(
        &entry(),
        MESSAGE,
        false,
        OffsetDateTime::now_utc(),
        &mut rng(),
    )
    .unwrap();
    verify(&cms, Content::Detached(MESSAGE), &[]).unwrap();
    assert!(matches!(
        verify(&cms, Content::Detached(b"other"), &[]),
        Err(Error::DigestMismatch)
    ));
}

#[test]
fn round_trip_hash_only() {
    let digest = SignerAlgorithm::Gost2015_512.digest(MESSAGE);
    let cms = create_cades_bes_from_hash(&entry(), &digest, OffsetDateTime::now_utc(), &mut rng())
        .unwrap();
    verify(&cms, Content::Digest(&digest), &[]).unwrap();
    verify(&cms, Content::Detached(MESSAGE), &[]).unwrap();
    assert!(matches!(
        create_cades_bes_from_hash(
            &entry(),
            &digest[..32],
            OffsetDateTime::now_utc(),
            &mut rng()
        ),
        Err(Error::Structure(_))
    ));
}

#[test]
fn add_signer_keeps_existing_signer_verbatim() {
    let later = FIXTURE_TIME + time::Duration::hours(1);
    // Attached: no data needed.
    let cms = add_signer(ATTACHED, &entry(), None, later, &mut rng()).unwrap();
    let sd = SignedData::from_der(&cms).unwrap();
    assert_eq!(sd.signer_infos.len(), 2);
    let orig = &SignedData::from_der(ATTACHED).unwrap().signer_infos[0];
    assert!(
        sd.signer_infos.iter().any(|s| s.raw == orig.raw),
        "original SignerInfo must be carried byte for byte"
    );
    assert_eq!(
        sd.certificates.len(),
        1,
        "same certificate is not duplicated"
    );
    assert_eq!(sd.digest_algorithms.len(), 1);
    let r = verify(&cms, Content::Attached, &[]).unwrap();
    assert_eq!(r.len(), 2);
    // Detached: data required.
    assert!(matches!(
        add_signer(DETACHED, &entry(), None, later, &mut rng()),
        Err(Error::ContentMissing)
    ));
    let cms = add_signer(DETACHED, &entry(), Some(MESSAGE), later, &mut rng()).unwrap();
    assert_eq!(
        verify(&cms, Content::Detached(MESSAGE), &[]).unwrap().len(),
        2
    );
    // Wrong data for an attached message is refused.
    assert!(matches!(
        add_signer(ATTACHED, &entry(), Some(b"x"), later, &mut rng()),
        Err(Error::DigestMismatch)
    ));
}

// ----- cross-check by the Kalkan oracle ------------------------------------

fn oracle() -> Option<PathBuf> {
    let run = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../tools/java-oracle/run.sh");
    let jar = std::env::var_os("KALKAN_JAR")
        .map(PathBuf::from)
        .or_else(|| {
            std::env::var_os("HOME").map(|h| {
                PathBuf::from(h)
                    .join(".config/NCALayer/ncalayer-cache/bundle10/version0.0/bundle.jar")
            })
        })?;
    if run.is_file() && jar.is_file() && Command::new("java").arg("-version").output().is_ok() {
        Some(run)
    } else {
        None
    }
}

fn oracle_verify(run: &Path, cms: &Path, data: Option<&Path>) -> String {
    let mut cmd = Command::new(run);
    cmd.arg("verifycms").arg(cms);
    if let Some(d) = data {
        cmd.arg(d);
    }
    let out = cmd.output().expect("run oracle");
    let stdout = String::from_utf8_lossy(&out.stdout).into_owned();
    assert!(
        out.status.success(),
        "oracle failed: {stdout}\n{}",
        String::from_utf8_lossy(&out.stderr)
    );
    stdout
}

#[test]
fn kalkan_oracle_verifies_our_cms() {
    let Some(run) = oracle() else {
        eprintln!("skipped: Kalkan oracle (JDK + NCALayer bundle.jar) not available");
        return;
    };
    let dir = std::env::temp_dir().join(format!("kz-cms-oracle-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    let data = dir.join("message.txt");
    std::fs::write(&data, MESSAGE).unwrap();
    let now = OffsetDateTime::now_utc();
    let e = entry();
    let digest = SignerAlgorithm::Gost2015_512.digest(MESSAGE);
    let cases: Vec<(&str, Vec<u8>, bool)> = vec![
        (
            "attached.cms",
            create_cades_bes(&e, MESSAGE, true, now, &mut rng()).unwrap(),
            false,
        ),
        (
            "detached.cms",
            create_cades_bes(&e, MESSAGE, false, now, &mut rng()).unwrap(),
            true,
        ),
        (
            "hash_only.cms",
            create_cades_bes_from_hash(&e, &digest, now, &mut rng()).unwrap(),
            true,
        ),
        (
            "two_signers.cms",
            add_signer(ATTACHED, &e, None, now, &mut rng()).unwrap(),
            false,
        ),
    ];
    for (name, cms, detached) in cases {
        let path = dir.join(name);
        std::fs::write(&path, &cms).unwrap();
        let out = oracle_verify(&run, &path, detached.then_some(data.as_path()));
        assert!(
            out.trim_end().ends_with("VALID") && !out.trim_end().ends_with("INVALID"),
            "{name}: {out}"
        );
        eprintln!(
            "oracle {name}: {}",
            out.trim_end().lines().last().unwrap_or("")
        );
    }
    let _ = std::fs::remove_dir_all(&dir);
}
